### PR TITLE
Added link to create issue in readme

### PR DESCRIPTION
**Pull request by IanLee1521**

### CODE REVIEW

**Comment by jayjaybillings** [comment]
Thanks @IanLee1521! Will you sign off your commit please? (-s option or check the box in Eclipse)

**Comment by IanLee1521** [comment]
Sure, I did this through the web UI which doesn't have support for that built in when you're editing (you can do it, but it has to be manual).

**Comment by IanLee1521** [comment]
Done.

**Comment by jayjaybillings** [comment]
@IanLee1521 sorry I missed this! The notification got lost in my email. Accepted. Thanks!

**Pull request merged**
